.TH TODOCLI 1 "24 December 2014"
.SH NAME
todocli \- command line todo manager
.SH SYNOPSIS
\fBtodocli\fP [\fIoptions\fP]
.LP
\fBtodocli\fP --help
.SH DESCRIPTION
Todocli aims....
.SH OPTIONS
.IP "\fB\-h\fR, \fB\-\-help\fR" 2
.IX Item "-h, --help"
Display help message and exit.
.IP "\fB\-d\fR \fI\s-1DELETE\s0\fR, \fB\-\-delete\fR \fI\s-1DELETE\s0\fR" 2
.IX Item "-d DATABASE, --database DATABASE"
.IP "\fB\-n\fR \fI\s-1NEW\s0\fR, \fB\-\-new\fR=\fI\s-1NEW\s0\fR" 2

.SH "AUTHORS"
.IX Header "AUTHORS"
Todocli was originally written by Hasan Tayyar BESIK <tayyar.besik@gmail.com>.
