.TH "TODOCLI" "1" "2015-07-10" "0.1" "William Moreno Reyes" ""
.SH "NAME"
todocli \- Command line To Do application
.SH "SYNOPSIS"
todocli [\-h |\-n <item> |\-d <id> ]
.SH "DESCRIPTION"
A command line ToDo application with SQLite backend powered by Python
.SH "OPTIONS"
.TP
\fB\-h \fP
\-\-help show help message and exit
.TP 
.TP
\fB\-n \fP
\-\-new <ITEM> new todo item
.TP 
\fB\-d \fP
\-\-delete <ID> delete a todo item with id 
.SH "AUTHOR"
Hasan Tayyar - Hüseyin Mert
